### ISSUE TITLE
Listing WIFI names returns NOT IMPLEMENTED in iOS

### ISSUE THREAD

**Issue by elmar001** [MousyBusiness/flutter_iot_wifi#2]
void _list() async {
    if (await _checkPermissions()) {
      FlutterIotWifi.list().then((value) => print("ssids: $value"));
    } else {
      print("don't have permission");
    }
  }
Returns: 
2022-07-06 15:10:54.893712+1000 Runner[2709:249993] flutter: NOT IMPLEMENTED

**Comment by MousyBusiness** [comment]
iOS has much stricter security around this sort of thing than Android. I believe it is not possible unfortunately.
